apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hls.configmapName" . }}
  labels:
    {{- include "hls.commonLabels" . | nindent 4 }}
    {{- include "hls.selectorLabels" . | nindent 4 }}
data:
  RABBITMQ_QUEUE: {{ .Values.config.rabbitmqQueue | quote }}
  API_PORT: {{ .Values.mainService.service.port | quote }}
  VIDEO_PROCESSOR_PORT: {{ .Values.videoProcessor.service.port | quote }}
  API_HEALTH_PATH: {{ .Values.config.apiHealthPath | quote }}
  API_READY_PATH: {{ .Values.config.apiReadyPath | quote }}
  WORKER_HEALTH_PATH: {{ .Values.config.workerHealthPath | quote }}
  WORKER_READY_PATH: {{ .Values.config.workerReadyPath | quote }}
  METRICS_PATH: {{ .Values.config.metricsPath | quote }}
  UPLOAD_DIR: {{ .Values.config.uploadDir | quote }}
  HLS_OUTPUT_DIR: {{ .Values.config.hlsDir | quote }}
