apiVersion: v1
kind: ConfigMap
metadata:
  name: hls-microservice-backend-config
data:
  MONGO_URI: {{ .Values.mongodb.uri | quote }}
  RABBITMQ_URL: {{ .Values.rabbitmq.url | quote }}
  RABBITMQ_QUEUE: {{ .Values.rabbitmq.queue | quote }}