{{- if and (.Values.mainService.enabled | or .Values.videoProcessor.enabled) .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hls.secretName" . }}
  labels:
    {{- include "hls.commonLabels" . | nindent 4 }}
    {{- include "hls.selectorLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  MONGO_URI: {{ required "secret.data.mongoUri is required" .Values.secret.data.mongoUri | quote }}
  RABBITMQ_URL: {{ required "secret.data.rabbitmqUrl is required" .Values.secret.data.rabbitmqUrl | quote }}
{{- end }}
